apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Provides a service for cross-site replication.
  labels:
    application: datagrid-service-xsite-hello-world
  name: datagrid-service-xsite
spec:
  ports:
  - port: 8660
    targetPort: 8660
    # Optional fixed nodePort to make debugging easier.
    nodePort: 32660
  selector:
    deploymentConfig: datagrid-service-xsite-hello-world
  type: NodePort
